services:
  - type: web
    name: verdantia-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
      - key: RENDER
        value: true
      - key: PYTHON_ENV
        value: production
